server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: academic-service
          uri: lb://academic-service
          predicates:
            - Path=/academic/**
        - id: question-service
          uri: lb://question-service
          predicates:
            - Path=/question/**
        - id: exam-service
          uri: lb://exam-service
          predicates:
            - Path=/exam/**
        - id: analysis-service
          uri: lb://analysis-service
          predicates:
            - Path=/analysis/**
        - id: suggestion-service
          uri: lb://suggestion-service
          predicates:
            - Path=/suggestion/**
        - id: audit-service
          uri: lb://audit-service
          predicates:
            - Path=/audit/**
