server:
    port: 8084

spring:
    application:
        name: exam-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/epqas_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: 123456
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848

mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true

encryption:
    aes:
        secret-key: 8e7d1cf04a923b5e06192d7cafe58031d46b972108fc5349ab721e8dc60f359b
        iv: 3d8a1f729c0e4b652817d9f35a0c81eb
